maturin publish called with -r https://test.pypi.org/legacy/
uploading again caused an error because the files already exists.

